export const MOCK_COMPET = [
  {
    "compet_name":
      "รายการแข่งขันกีฬากรีฑา ชิงชนะเงินรางวัล กองทุนพัฒนาการกีฬาแห่งชาติ",
    "date_start": "2023-6-12",
    "date_end": "2023-6-14",
    "compet_year": 2023,
    "location": "สนามการกีฬาแห่งประเทศไทย",
    "number_participants": 10,
    "compet_level": "ระดับทั่วไป",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "pending"
  },
  {
    "compet_name":
      "รายการแข่งขันกีฬากรีฑา ชิงชนะเงินรางวัล กองทุนพัฒนาการกีฬาแห่งชาติ",
    "date_start": "2023-5-11",
    "date_end": "2023-5-13",
    "compet_year": 2023,
    "location": "สนามการกีฬาแห่งประเทศไทย",
    "number_participants": 10,
    "compet_level": "ระดับทั่วไป",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "pending"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑา รอบคัดเลือกระดับ ครั้งที่ 5",
    "date_start": "2022-10-20",
    "date_end": "2022-10-21",
    "compet_year": 2022,
    "location": "สมาคมศุกชลาลัย แขวงวังใหม่ เขตปทุมวัน กรุงเทพมหานคร",
    "number_participants": 10,
    "compet_level": "ระดับภาค",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑา รอบคัดเลือกระดับ ครั้งที่ 4",
    "date_start": "2022-10-18",
    "date_end": "2022-10-19",
    "compet_year": 2022,
    "location": "สมาคมศุกชลาลัย แขวงวังใหม่ เขตปทุมวัน กรุงเทพมหานคร",
    "number_participants": 20,
    "compet_level": "ระดับภาค",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑา รอบคัดเลือกระดับ ครั้งที่ 3",
    "date_start": "2022-10-16",
    "date_end": "2022-10-17",
    "compet_year": 2022,
    "location": "สมาคมศุกชลาลัย แขวงวังใหม่ เขตปทุมวัน กรุงเทพมหานคร",
    "number_participants": 20,
    "compet_level": "ระดับภาค",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 1",
    "compet_reward": "gold"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑา รอบคัดเลือกระดับ ครั้งที่ 2",
    "date_start": "2022-10-14",
    "date_end": "2022-10-15",
    "compet_year": 2022,
    "location": "สมาคมศุกชลาลัย แขวงวังใหม่ เขตปทุมวัน กรุงเทพมหานคร",
    "number_participants": 24,
    "compet_level": "ระดับภาค",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 1",
    "compet_reward": "gold"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑา รอบคัดเลือกระดับ ครั้งที่ 1",
    "date_start": "2022-10-12",
    "date_end": "2022-10-13",
    "compet_year": 2022,
    "location": "สมาคมศุกชลาลัย แขวงวังใหม่ เขตปทุมวัน กรุงเทพมหานคร",
    "number_participants": 30,
    "compet_level": "ระดับภาค",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 1",
    "compet_reward": "gold"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑา ระดับนานาชาติ ครั้งที่ 7",
    "date_start": "2022-09-25",
    "date_end": "2022-09-26",
    "compet_year": 2022,
    "location": "Sport national stadium Bangkok Siam",
    "number_participants": 50,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 3",
    "compet_reward": "bronze"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑา ระดับนานาชาติ ครั้งที่ 6",
    "date_start": "2022-09-22",
    "date_end": "2022-09-24",
    "compet_year": 2022,
    "location": "Sport national stadium Bangkok Siam",
    "number_participants": 50,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑา ระดับนานาชาติ ครั้งที่ 5",
    "date_start": "2022-08-30",
    "date_end": "2022-08-35",
    "compet_year": 2022,
    "location": "Sport national stadium Bangkok Siam",
    "number_participants": 50,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑา ระดับนานาชาติ ครั้งที่ 4",
    "date_start": "2022-08-28",
    "date_end": "2022-08-32",
    "compet_year": 2022,
    "location": "Sport national stadium Bangkok Siam",
    "number_participants": 50,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 3",
    "compet_reward": "bronze"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑา ระดับนานาชาติ ครั้งที่ 3",
    "date_start": "2022-08-26",
    "date_end": "2022-08-29",
    "compet_year": 2022,
    "location": "Sport national stadium Bangkok Siam",
    "number_participants": 50,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑา ระดับนานาชาติ ครั้งที่ 2",
    "date_start": "2022-08-24",
    "date_end": "2022-08-26",
    "compet_year": 2022,
    "location": "Sport national stadium Bangkok Siam",
    "number_participants": 50,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑา ระดับนานาชาติ ครั้งที่ 1",
    "date_start": "2022-08-22",
    "date_end": "2022-08-23",
    "compet_year": 2022,
    "location": "Sport national stadium Bangkok Siam",
    "number_participants": 50,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑาเยาวชนระดับเขต",
    "date_start": "2022-03-08",
    "date_end": "2022-03-9",
    "compet_year": 2022,
    "location": "สนามการกีฬา ศูนย์เยาวชนกีฬาเขตบางกะปิ",
    "number_participants": 30,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 3",
    "compet_reward": "bronze"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑาเยาวชนระดับเขต",
    "date_start": "2022-03-6",
    "date_end": "2022-03-7",
    "compet_year": 2022,
    "location": "สนามการกีฬา ศูนย์เยาวชนกีฬาเขตบางกะปิ",
    "number_participants": 30,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑาเยาวชนระดับเขต",
    "date_start": "2022-03-5",
    "date_end": "2022-03-7",
    "compet_year": 2022,
    "location": "สนามการกีฬา ศูนย์เยาวชนกีฬาเขตบางกะปิ",
    "number_participants": 30,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑาเยาวชนระดับเขต",
    "date_start": "2022-03-4",
    "date_end": "2022-03-5",
    "compet_year": 2022,
    "location": "สนามการกีฬา ศูนย์เยาวชนกีฬาเขตบางกะปิ",
    "number_participants": 20,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑาเยาวชนระดับเขต",
    "date_start": "2022-03-2",
    "date_end": "2022-03-3",
    "compet_year": 2022,
    "location": "สนามการกีฬา ศูนย์เยาวชนกีฬาเขตบางกะปิ",
    "number_participants": 20,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 3",
    "compet_reward": "bronze"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑาเยาวชน กรุงเทพมหานคร",
    "date_start": "2021-06-22",
    "date_end": "2021-06-23",
    "compet_year": 2021,
    "location": "สนามการกีฬาแห่งประเทศไทย",
    "number_participants": 50,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑาเยาวชน กรุงเทพมหานคร",
    "date_start": "2021-06-20",
    "date_end": "2021-06-21",
    "compet_year": 2021,
    "location": "สนามการกีฬาแห่งประเทศไทย",
    "number_participants": 10,
    "compet_level": "ระดับภาค",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑาเยาวชน กรุงเทพมหานคร",
    "date_start": "2021-06-18",
    "date_end": "2021-06-19",
    "compet_year": 2021,
    "location": "สนามการกีฬาแห่งประเทศไทย",
    "number_participants": 20,
    "compet_level": "ระดับภาค",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑาเยาวชน กรุงเทพมหานคร",
    "date_start": "2021-06-16",
    "date_end": "2021-06-17",
    "compet_year": 2021,
    "location": "สนามการกีฬาแห่งประเทศไทย",
    "number_participants": 20,
    "compet_level": "ระดับภาค",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 1",
    "compet_reward": "gold"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑาเยาวชน กรุงเทพมหานคร",
    "date_start": "2021-06-14",
    "date_end": "2021-06-15",
    "compet_year": 2021,
    "location": "สนามการกีฬาแห่งประเทศไทย",
    "number_participants": 24,
    "compet_level": "ระดับภาค",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 1",
    "compet_reward": "gold"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑาเยาวชน กรุงเทพมหานคร",
    "date_start": "2021-06-12",
    "date_end": "2021-06-13",
    "compet_year": 2021,
    "location": "สนามการกีฬาแห่งประเทศไทย",
    "number_participants": 30,
    "compet_level": "ระดับภาค",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 1",
    "compet_reward": "gold"
  },
  {
    "compet_name": "รายการแข่งขันกีฬากรีฑาเยาวชนระดับเขต",
    "date_start": "2021-02-8",
    "date_end": "2021-02-10",
    "compet_year": 2021,
    "location": "สนามการกีฬา ศูนย์เยาวชนกีฬาเขตบางกะปิ",
    "number_participants": 30,
    "compet_level": "ระดับนานาชาติ",
    "compet_type": "แข่งเดี่ยว",
    "sport_type": "วิ่งมาราธอน",
    "compet_status": "done",
    "compet_result": "ชนะเลิศอันดับที่ 2",
    "compet_reward": "sliver"
  }
]
